name: AuthorizationService

on:
  push:
    branches: [ master ]
    paths:
      - src/Services/AuthorizationService/**
      - .github/workflows/authorization-service.yaml
  pull_request:
    branches: [ master ]
    paths:
      - src/Services/AuthorizationService/**

# defaults:
#   run:
#     working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-docker:
    needs: [ build ]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker AuthorizationService image
        run: docker build . --file Services/AuthorizationService/Rest/Dockerfile
        
  publish-docker:
    if: contains(github.ref, 'master')
    needs: [ build-docker ]
    runs-on: ubuntu-20.04
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: rvalkenburg/kwetter-authorization-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: src
        dockerfile: Services/AuthorizationService/Rest/Dockerfile   
        tags: "latest, ${{ steps.date.outputs.date }}"
  
#   update-deployment:
#     needs: [ publish-docker ]
#     runs-on: ubuntu-20.04
#     steps:
#     - name: Azure Login
#       uses: Azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#     - name: Azure CLI Action
#       uses: Azure/cli@1.0.4
#       with:
#         inlineScript: kubectl rollout restart deployment kwetter-authorization-service


  
